<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your username is invalid</name>
   <tag></tag>
   <elementGuidId>8c403a33-7c27-4c95-a14d-04713bb04060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b4c146e-d548-469f-aaa4-848fb98899d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flash</value>
      <webElementGuid>1f6d792c-68ab-4270-a435-5517e9062a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flash error</value>
      <webElementGuid>b56ba78c-e047-4c06-9c5d-983a113ec9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Your username is invalid!
            ×
          </value>
      <webElementGuid>3d244972-5920-42ff-85aa-598749353e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash&quot;)</value>
      <webElementGuid>db9276c3-7048-4ebd-885f-a7e0566894be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flash']</value>
      <webElementGuid>e7db19ee-6ce5-411d-8146-4198e3cb554b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flash-messages']/div</value>
      <webElementGuid>8c9f048d-0ff8-40f0-b653-3bd82a343124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Page'])[1]/preceding::div[1]</value>
      <webElementGuid>6af80993-870b-41c2-aab0-4bdc6b0746fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tomsmith'])[1]/preceding::div[1]</value>
      <webElementGuid>01495185-47b7-40b1-bdd7-ca637c145074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your username is invalid!']/parent::*</value>
      <webElementGuid>ce3507e2-b137-4ed5-aff2-67db1adec62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>3bd5d5a7-e604-426b-99d9-af34d72e1e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flash' and (text() = '
            Your username is invalid!
            ×
          ' or . = '
            Your username is invalid!
            ×
          ')]</value>
      <webElementGuid>72efd0ec-3446-47a3-851b-7e76a2d14bed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
