<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Welcome to the Secure Area. When you are done click logout below</name>
   <tag></tag>
   <elementGuidId>16607aa0-2f41-4007-b63f-0c961bfee634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.subheader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ff558d4a-1526-43ec-a12a-41217440c61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subheader</value>
      <webElementGuid>6c0b2d91-b3ae-4564-9947-3e1d0855bcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to the Secure Area. When you are done click logout below.</value>
      <webElementGuid>f0ea64f4-84fa-4c7b-91b2-868e37f92be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/h4[@class=&quot;subheader&quot;]</value>
      <webElementGuid>8860d814-7785-49ec-8098-9f8b2e2e022e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/h4</value>
      <webElementGuid>d37fee23-488b-4668-a468-84005931e85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Area'])[1]/following::h4[1]</value>
      <webElementGuid>a3d91e8f-41d8-40a9-99f2-35bd43f341e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::h4[1]</value>
      <webElementGuid>c82c3b62-60fe-47e8-9e57-bd136ceacfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome to the Secure Area. When you are done click logout below.']/parent::*</value>
      <webElementGuid>18f9fb51-edf3-4a4b-a047-4d12fecb44bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>627c6412-5866-4a7a-800a-221d33473f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Welcome to the Secure Area. When you are done click logout below.' or . = 'Welcome to the Secure Area. When you are done click logout below.')]</value>
      <webElementGuid>a780d547-e076-4079-80f4-85b597f8668e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
